---
title: "Untitled"
author: "Matt Ryan"
date: "2024-08-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse)
```


```{r, message=FALSE}
model_types <- c("rf", "xgboost")
model_numbers <- c("model_1", "model_2")
features_list <- list()
cc <- 1
for(model_number in model_numbers){
  for(model_type in model_types){
    # if(model_number=="model_1"){
    #   target="face masks"
    # }else{
    #   target="general behaviour"
    # }
    
    features_list[[cc]] <- read_csv(here::here(glue::glue("results/{model_number}a_{model_type}_feature_importance.csv")),
                                    col_types = cols(), col_select = -1) %>% 
      mutate(model = model_type,
             target = model_number,
             period = "pre-mandate")
    cc <- cc+1
    features_list[[cc]] <- read_csv(here::here(glue::glue("results/{model_number}b_{model_type}_feature_importance.csv")),
                                    col_types = cols(), col_select = -1) %>% 
      mutate(model = model_type,
             target = model_number,
             period = "during mandate")
    cc <- cc+1
  }
}
feature_df <- do.call(bind_rows, features_list)
```

```{r}
feature_summaries<-feature_df %>% 
  pivot_longer(-c(model, target, period)) %>%  
  drop_na() %>%  #protective no mask not measured in general behaviour model
  group_by(model, target, period, name) %>% 
  summarise(mean_importance = median(value),
            std = sd(value)/sqrt(n()),
            q1 = quantile(value, 0.25),
            q2 = quantile(value, 0.75),
            .groups = "drop") 
```

```{r}
key_features <- feature_summaries %>% 
  group_by(model, target, period) %>% 
  arrange(-mean_importance) %>% 
  filter(!str_detect(name, "state")) %>% 
  slice(1:10) %>% 
  ungroup() %>% 
  mutate(name = ifelse(str_detect(name, "PHQ4_1"), "PHQ4_1", name),
         name = ifelse(str_detect(name, "PHQ4_2"), "PHQ4_2", name),
         name = ifelse(str_detect(name, "PHQ4_3"), "PHQ4_3", name),
         name = ifelse(str_detect(name, "PHQ4_4"), "PHQ4_4", name),
         name = ifelse(str_detect(name, "WCRex1"), "WCRex1", name),
         name = ifelse(str_detect(name, "WCRex2"), "WCRex2", name),
         name = ifelse(str_detect(name, "employment_status"), "employment_status", name),
         name = ifelse(str_detect(name, "gender"), "gender", name),
         name = ifelse(str_detect(name, "i9_health"), "i9_health", name),
         name = ifelse(str_detect(name, "i11_health"), "i11_health", name),
  ) %>% 
  distinct(target, period, name, .keep_all = TRUE) 
```

```{r}
key_features_pre_mask <- key_features %>% 
  filter(period=="pre-mandate", target=="model_1") %>% 
  pull(name)
key_features_during_mask <- key_features %>% 
  filter(period!="pre-mandate", target=="model_1")%>% 
  pull(name)
key_features_pre_gen <- key_features %>% 
  filter(period=="pre-mandate", target!="model_1") %>% 
  pull(name)
key_features_during_gen <- key_features %>% 
  filter(period!="pre-mandate", target!="model_1")%>% 
  pull(name)
```

```{r}
common_features_mask <- intersect(key_features_pre_mask, key_features_during_mask)

distinct_pre_mask <- key_features_pre_mask[!str_detect(key_features_pre_mask, 
                                                  str_c(common_features_mask, collapse = "|"))]
distinct_during_mask <- key_features_during_mask[!str_detect(key_features_during_mask, 
                                                             str_c(common_features_mask, collapse = "|"))]

common_features_gen <- intersect(key_features_pre_gen, key_features_during_gen)

distinct_pre_gen <- key_features_pre_gen[!str_detect(key_features_pre_gen, 
                                                 str_c(common_features_gen, collapse = "|"))]
distinct_during_gen <- key_features_during_gen[!str_detect(key_features_during_gen, 
                                                           str_c(common_features_gen, collapse = "|"))]
```


```{r}
clean_data <- read_csv(here::here("data/cleaned_data.csv"),
                       col_types = cols())
clean_data_w_mandate <- read_csv(here::here("data/cleaned_data_preprocessing.csv"),
                                 col_types = cols()) %>% 
  select(RecordNo, within_mandate_period)
full_data <-left_join(clean_data, clean_data_w_mandate, by="RecordNo") %>% 
  mutate(within_mandate_period = ifelse(within_mandate_period==0, "No", "Yes"))
```

```{r}
df_pre_mandate_mask<-full_data %>% 
  select(face_mask_behaviour_binary,
         within_mandate_period,
         all_of(distinct_pre_mask)) %>% 
  filter(within_mandate_period=="No")

df_pre_mandate_gen<-full_data %>% 
  select(protective_behaviour_binary,
         within_mandate_period,
         all_of(distinct_pre_gen)) %>% 
  filter(within_mandate_period=="No")

df_during_mandate_mask<-full_data %>% 
  select(face_mask_behaviour_binary,
         within_mandate_period,
         all_of(distinct_during_mask))%>% 
  filter(within_mandate_period=="Yes")

df_during_mandate_gen<-full_data %>% 
  select(protective_behaviour_binary,
         within_mandate_period,
         all_of(distinct_during_gen))%>% 
  filter(within_mandate_period=="Yes")

df_common_mask <- full_data %>% 
  select(face_mask_behaviour_binary,
         within_mandate_period,
         all_of(common_features_mask))
df_common_gen <- full_data %>% 
  select(protective_behaviour_binary,
         within_mandate_period,
         all_of(common_features_gen))
```

```{r}
df_common_mask %>% 
  ggplot(aes(y=face_mask_behaviour_binary, x=i2_health,
             fill=face_mask_behaviour_binary)) +
  geom_violin() +
  facet_wrap(~within_mandate_period, labeller = label_both) +
  labs(y="Face mask usage", fill="Face mask usage",) +
  theme_bw() +
  theme(legend.position = "bottom")
```
```{r}
tmp <- full_data %>% 
  select(protective_behaviour_binary,
         within_mandate_period,
         var=all_of(common_features_gen[8]))
```

```{r}
is.character(tmp$var)
```

```{r}
tmp %>% 
  count(protective_behaviour_binary, within_mandate_period, var) %>% 
  pivot_wider(names_from=var, values_from = n) %>% 
  arrange(within_mandate_period)
```





